[package]
name = "phylo2vec"
version = "0.1.0"
authors = ["Neil Scheidwasser <neil.clow@sund.ku.dk>"]
edition = "2021"
description = "Phylo2Vec: integer vector representation of binary (phylogenetic) trees"
license = "LGPL-3.0"

[dependencies]
rand = "*"

[dev-dependencies]
rstest = "0.23.0"
criterion = { version = "0.5", features = ["html_reports"] }


[[bench]]
name = "bench_main"
harness = false

[lib]
bench = false
