name: CI Python

on:
  push:
    branches:
      - main
      - dev
  pull_request:

permissions:
  contents: read

env:
  PIXI_PYTHON_ENV: py-phylo2vec
  PIXI_COLOR: always

jobs:
  build_and_test:
    name: Python project - latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          environments: ${{ env.PIXI_PYTHON_ENV }}
      - run: pixi run -e ${{ env.PIXI_PYTHON_ENV }} test
